# Generated by Django 5.2.6 on 2025-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='learninggoal',
            name='unique_primary_goal_per_profile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='unique_primary_goal_per_profile', violation_error_message='Only one primary goal is allowed per profile.'),
        ),
    ]
