# Generated by Django 5.2.6 on 2025-09-24 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_modulegame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMeetingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_activities', to='core.coursemodule')),
            ],
            options={
                'verbose_name': 'Module meeting activity',
                'verbose_name_plural': 'Module meeting activities',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
