# Generated by Django 5.2.6 on 2025-09-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_modulemeetingactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulegame',
            name='game_type',
            field=models.CharField(choices=[('letter-sequence', 'Letter Sequence'), ('adaptive-flashcards', 'Adaptive Flashcards')], default='letter-sequence', max_length=32),
        ),
        migrations.CreateModel(
            name='ModuleGameFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('word', models.CharField(max_length=80)),
                ('image_url', models.URLField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.modulegame')),
            ],
            options={
                'verbose_name': 'Adaptive flashcard',
                'verbose_name_plural': 'Adaptive flashcards',
                'ordering': ['game', 'order', 'id'],
                'unique_together': {('game', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ModuleGameFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_index', models.PositiveSmallIntegerField(default=0)),
                ('next_review_at', models.DateTimeField()),
                ('correct_streak', models.PositiveSmallIntegerField(default=0)),
                ('seen_count', models.PositiveIntegerField(default=0)),
                ('last_outcome', models.CharField(blank=True, max_length=12)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='core.modulegameflashcard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to='core.profile')),
            ],
            options={
                'verbose_name': 'Adaptive flashcard progress',
                'verbose_name_plural': 'Adaptive flashcard progress',
                'ordering': ['profile', 'flashcard'],
            },
        ),
        migrations.CreateModel(
            name='ModuleGameFlashcardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=12)),
                ('streak_length', models.PositiveSmallIntegerField(default=0)),
                ('time_spent_ms', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.modulegameflashcardprogress')),
            ],
            options={
                'verbose_name': 'Adaptive flashcard log',
                'verbose_name_plural': 'Adaptive flashcard logs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='modulegameflashcardprogress',
            index=models.Index(fields=['profile', 'next_review_at'], name='flashcard_progress_due_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modulegameflashcardprogress',
            unique_together={('profile', 'flashcard')},
        ),
    ]
