# Generated by Django 5.2.6 on 2025-09-25 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_modulegame_game_type_modulegameflashcard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAfterburnerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('talk-record', 'Talk & Record'), ('reading', 'Read & Highlight'), ('real-world', 'Real World Challenge'), ('grammar', 'Grammar Snapshot'), ('game', 'Game Mission')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afterburner_activity', to='core.modulegame')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afterburner_activities', to='core.coursemodule')),
            ],
            options={
                'verbose_name': 'Stage 3 · Afterburner activity',
                'verbose_name_plural': 'Stage 3 · Afterburner activities',
                'ordering': ['module', 'slot'],
                'unique_together': {('module', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='ModuleFlightDeckActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('scheduler', 'Meeting Scheduler'), ('notebook', 'Notebook Prep'), ('recorder', 'Mission Recorder')], max_length=32)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=120)),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightdeck_activities', to='core.coursemodule')),
            ],
            options={
                'verbose_name': 'Stage 2 · Flight Deck activity',
                'verbose_name_plural': 'Stage 2 · Flight Deck activities',
                'ordering': ['module', 'order', 'slot'],
                'unique_together': {('module', 'slot')},
            },
        ),
    ]
