# Generated by Django 5.2.6 on 2025-09-25 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_moduleafterburneractivity_moduleflightdeckactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLaunchPadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=120)),
                ('link_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launchpad_tasks', to='core.coursemodule')),
            ],
            options={
                'verbose_name': 'Stage 1 · Launch Pad activity',
                'verbose_name_plural': 'Stage 1 · Launch Pad activities',
                'ordering': ['module', 'order', 'id'],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
