# Generated by Django 5.2.6 on 2025-09-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_modulelaunchpadtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulelaunchpadtask',
            options={'ordering': ['module', 'order', 'id'], 'verbose_name': 'Stage 1 · Launch Pad task', 'verbose_name_plural': 'Stage 1 · Launch Pad tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='modulelaunchpadtask',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='modulelaunchpadtask',
            name='module',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launchpad_tasks', to='core.coursemodule'),
        ),
        migrations.CreateModel(
            name='ModuleLaunchPadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='launchpad_activity', to='core.coursemodule')),
            ],
            options={
                'verbose_name': 'Stage 1 · Launch Pad set',
                'verbose_name_plural': 'Stage 1 · Launch Pad sets',
            },
        ),
        migrations.AddField(
            model_name='modulelaunchpadtask',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.modulelaunchpadactivity'),
        ),
    ]
