# Generated by Django 5.2.6 on 2025-09-25 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_launchpad_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAfterburnerGrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('formula', models.CharField(max_length=160)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_points', to='core.moduleafterburneractivity')),
            ],
            options={
                'verbose_name': 'Afterburner grammar pattern',
                'verbose_name_plural': 'Afterburner grammar patterns',
                'ordering': ['activity', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'order'), name='unique_grammar_point_order_per_activity')],
            },
        ),
        migrations.CreateModel(
            name='ModuleAfterburnerReadingChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_chapters', to='core.moduleafterburneractivity')),
            ],
            options={
                'verbose_name': 'Afterburner reading chapter',
                'verbose_name_plural': 'Afterburner reading chapters',
                'ordering': ['activity', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'order'), name='unique_reading_chapter_order_per_activity')],
            },
        ),
    ]
