# Generated by Django 5.2.6 on 2025-09-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_moduleafterburnergrammarpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAfterburnerStage',
            fields=[
            ],
            options={
                'verbose_name': 'Stage 3 · Afterburner editor',
                'verbose_name_plural': 'Stage 3 · Afterburner editors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.coursemodule',),
        ),
    ]
