# Generated by Django 5.2.6 on 2025-09-27 01:55

from django.db import migrations, models


def set_flashcard_type(apps, schema_editor):
    ModuleGame = apps.get_model('core', 'ModuleGame')
    ModuleGame.objects.filter(game_type='letter-sequence').update(
        game_type='adaptive-flashcards'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_moduleafterburnerstage'),
    ]

    operations = [
        migrations.RunPython(set_flashcard_type, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='modulegame',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='modulegame',
            name='word',
        ),
        migrations.AlterField(
            model_name='modulegame',
            name='game_type',
            field=models.CharField(choices=[('adaptive-flashcards', 'Adaptive Flashcards')], default='adaptive-flashcards', max_length=32),
        ),
    ]
