# Generated by Django 5.2.6 on 2025-09-30 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_modulegame_definition_remove_modulegame_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleafterburneractivity',
            name='goal',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='ModuleAfterburnerRealWorldStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('instruction', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_world_steps', to='core.moduleafterburneractivity')),
            ],
            options={
                'verbose_name': 'Afterburner real-world instruction',
                'verbose_name_plural': 'Afterburner real-world instructions',
                'ordering': ['activity', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'order'), name='unique_real_world_step_order_per_activity')],
            },
        ),
        migrations.RemoveField(
            model_name='modulegameflashcard',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='modulegameflashcard',
            name='image_url',
        ),
        migrations.AddField(
            model_name='modulegameflashcard',
            name='meaning',
            field=models.TextField(blank=True),
        ),
    ]
