# Generated by Django 5.2.6 on 2025-10-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sync_flashcard_meaning_and_step_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemeetingactivity',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulemeetingactivity',
            name='grammar_formula',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='ModuleMeetingActivityInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='core.modulemeetingactivity')),
            ],
            options={
                'verbose_name': 'Module meeting instruction',
                'verbose_name_plural': 'Module meeting instructions',
                'ordering': ['activity', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'order'), name='unique_meeting_instruction_order_per_activity')],
            },
        ),
        migrations.CreateModel(
            name='ModuleMeetingPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paired_with_assistant', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='core.modulemeetingactivity')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='core.modulelivemeeting')),
                ('module', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_pairings', to='core.coursemodule')),
                ('profile_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_pairings_as_partner', to='core.profile')),
                ('profile_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_pairings_as_primary', to='core.profile')),
            ],
            options={
                'verbose_name': 'Module meeting pairing',
                'verbose_name_plural': 'Module meeting pairings',
                'ordering': ['meeting', 'activity', 'profile_primary'],
                'constraints': [models.UniqueConstraint(fields=('meeting', 'activity', 'profile_primary'), name='unique_primary_per_activity_pairing'), models.CheckConstraint(condition=models.Q(models.Q(('paired_with_assistant', True), ('profile_partner__isnull', True)), models.Q(('paired_with_assistant', False), ('profile_partner__isnull', False)), _connector='OR'), name='meeting_pair_partner_presence')],
            },
        ),
    ]
