"""Core URL routes for FOREIGN."""
from django.urls import path

from .views import (
    AuthLoginView,
    CourseDetailView,
    CourseEnrollView,
    CourseListView,
    DashboardView,
    ExperiencesView,
    MethodView,
    PricingView,
    ProgramDetailView,
    ProgramListView,
    PromiseView,
    AccountView,
    PlacementExamView,
    CourseModuleDetailView,
    CourseModuleStageView,
    ModuleStageTaskToggleView,
    GoalManageView,
    ProgressCreateView,
    AvailabilityManageView,
    AssessmentUploadView,
    landing,
    logout_view,
    register,
)

urlpatterns = [
    path("", landing, name="landing"),
    path("login/", AuthLoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
    path("register/", register, name="register"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("account/", AccountView.as_view(), name="account"),
    path("courses/", CourseListView.as_view(), name="course_list"),
    path("courses/<slug:slug>/", CourseDetailView.as_view(), name="course_detail"),
    path("courses/<slug:slug>/enroll/", CourseEnrollView.as_view(), name="course_enroll"),
    path("courses/<slug:slug>/module/<int:order>/", CourseModuleDetailView.as_view(), name="course_module"),
    path(
        "courses/<slug:slug>/module/<int:order>/<str:stage>/",
        CourseModuleStageView.as_view(),
        name="course_module_stage",
    ),
    path(
        "courses/<slug:slug>/module/<int:order>/<str:stage>/task/<int:index>/toggle/",
        ModuleStageTaskToggleView.as_view(),
        name="course_module_stage_task_toggle",
    ),
    path("promise/", PromiseView.as_view(), name="promise"),
    path("method/", MethodView.as_view(), name="method"),
    path("experiences/", ExperiencesView.as_view(), name="experiences"),
    path("pricing/", PricingView.as_view(), name="pricing"),
    path("programs/", ProgramListView.as_view(), name="program_list"),
    path("placement-exam/", PlacementExamView.as_view(), name="placement_exam"),
    path("goals/manage/", GoalManageView.as_view(), name="manage_goal"),
    path("progress/add/", ProgressCreateView.as_view(), name="progress_add"),
    path("availability/manage/", AvailabilityManageView.as_view(), name="availability_manage"),
    path("assessments/upload/", AssessmentUploadView.as_view(), name="assessment_upload"),
    path("programs/<str:code>/", ProgramDetailView.as_view(), name="program_detail"),
]
